package SistemadePagos;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author DZS1212
 */
public class GUIPagos extends javax.swing.JFrame {

    MetodoPago pg;
    Bizum bz = new Bizum();
    PayPal pp = new PayPal();
    Tarjeta tj = new Tarjeta();

    /**
     * Creates new form GUIPagos
     */
    public GUIPagos() {
        initComponents();
        setFrame();
        this.Pantalla.setText("Binvenido al Programa de Pagos\nSelecciona un metodo para comenzar");
    }

    private void setFrame() {
        this.setTitle("Pagos");
        this.setSize(new Dimension(400, 700));
        this.pack();
        this.setLocationRelativeTo(null);
    }

    private void validacionPago(String entrada) throws Exception {

        if (entrada != null && !entrada.isEmpty()) {
            try {
                double dinero = Double.parseDouble(entrada);
                if (dinero <= 0) {
                    throw new Exception("No puedes pagar una cantidad negativa");
                }
                pg.pagar(dinero);

            } catch (Exception e) {
                this.ErrorLabel.setText("No has introducido numeros");
            }
            this.Pantalla.setText(pg.obtenerComprobante());
        } else {
            throw new Exception("Entrada Vacia");
        }
    }

    private void validacionBizum(String entrada) throws Exception {
        this.ErrorLabel.setText("");
        if (entrada != null && !entrada.isEmpty()) {
            if (entrada.isEmpty()) {
                throw new Exception("No has introducido nada");
            } else if (!entrada.matches("\\d{9}")) {
                throw new Exception("Su tarjeta no contiene un formato adecuado(16 Numeros)");
            } else {
                pg.set(entrada);
                actualizarUI();
            }
        } else {
            throw new Exception("Entrada Vacia");
        }

    }

    private void validacionTarjetas(String entrada) throws Exception {
        this.ErrorLabel.setText("");
        if (entrada != null && !entrada.isEmpty()) {
            if (entrada.isEmpty()) {
                throw new Exception("No has introducido nada");
            } else if (!entrada.matches("\\d{16}")) {
                throw new Exception("Su tarjeta no contiene un formato adecuado(16 Numeros)");
            } else {
                pg.set(entrada);
                actualizarUI();
            }
        } else {
            throw new Exception("Entrada Vacia");
        }
    }

    private void validacionPayPal(String entrada) throws Exception {
        this.ErrorLabel.setText("");
        if (entrada != null && !entrada.isEmpty()) {
            if (!entrada.matches("[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}")) {
                throw new Exception("Su correo no tiene el formato deseado (a@b.c)");
            } else {
                pg.set(entrada);
                actualizarUI();
            }
        } else {
            throw new Exception("Entrada Vacia");
        }
    }

    private void actualizarUI() {
        this.Pantalla.setText("Metodo de pago seleccionado: " + pg.getClass().getSimpleName() + "\nDatos Introducidos:" + pg.get());
        this.ErrorLabel.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pagar = new javax.swing.JButton();
        PayPal = new javax.swing.JButton();
        Tarjeta = new javax.swing.JButton();
        Bizum = new javax.swing.JButton();
        Metodos = new javax.swing.JLabel();
        Mensajes = new javax.swing.JPanel();
        Pantalla = new javax.swing.JTextArea();
        ErrorLabel = new javax.swing.JTextField();
        LogoBanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setResizable(false);

        Pagar.setText("Pagar");
        Pagar.setFocusable(false);
        Pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagarActionPerformed(evt);
            }
        });

        PayPal.setText("PayPal");
        PayPal.setFocusable(false);
        PayPal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayPalActionPerformed(evt);
            }
        });

        Tarjeta.setText("Tarjeta");
        Tarjeta.setFocusable(false);
        Tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarjetaActionPerformed(evt);
            }
        });

        Bizum.setText("Bizum");
        Bizum.setFocusable(false);
        Bizum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BizumActionPerformed(evt);
            }
        });

        Metodos.setText("Metodos de Pago:");

        Pantalla.setEditable(false);
        Pantalla.setBackground(new java.awt.Color(0, 153, 204));
        Pantalla.setColumns(20);
        Pantalla.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        Pantalla.setForeground(new java.awt.Color(0, 0, 0));
        Pantalla.setLineWrap(true);
        Pantalla.setRows(5);
        Pantalla.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(153, 153, 153)));
        Pantalla.setFocusable(false);

        ErrorLabel.setEditable(false);
        ErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        ErrorLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ErrorLabel.setToolTipText("");
        ErrorLabel.setCaretColor(new java.awt.Color(255, 0, 51));
        ErrorLabel.setFocusable(false);

        javax.swing.GroupLayout MensajesLayout = new javax.swing.GroupLayout(Mensajes);
        Mensajes.setLayout(MensajesLayout);
        MensajesLayout.setHorizontalGroup(
            MensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MensajesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ErrorLabel)
                    .addComponent(Pantalla))
                .addContainerGap())
        );
        MensajesLayout.setVerticalGroup(
            MensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MensajesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        LogoBanco.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Mensajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Metodos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bizum, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PayPal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tarjeta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(LogoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Pagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Bizum, PayPal, Tarjeta});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Mensajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Metodos)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Bizum)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Tarjeta))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(LogoBanco)))))
                .addGap(18, 18, 18)
                .addComponent(PayPal)
                .addGap(22, 22, 22)
                .addComponent(Pagar)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Bizum, PayPal, Tarjeta});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BizumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BizumActionPerformed
        pg = bz;
        this.ErrorLabel.setText("");
        String entrada = JOptionPane.showInputDialog(this, "Introduzca numero de telefono", "Bizum", JOptionPane.PLAIN_MESSAGE);
        try {
            validacionBizum(entrada);
        } catch (Exception ex) {
            this.ErrorLabel.setText(ex.getMessage());
        }
    }//GEN-LAST:event_BizumActionPerformed

    private void TarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarjetaActionPerformed
        pg = tj;
        this.ErrorLabel.setText("");
        String entrada = JOptionPane.showInputDialog(this, "Introduzca numero de tarjeta", "Tarjeta", JOptionPane.PLAIN_MESSAGE);
        try {
            validacionTarjetas(entrada);
        } catch (Exception ex) {
            this.ErrorLabel.setText(ex.getMessage());
        }
    }//GEN-LAST:event_TarjetaActionPerformed

    private void PayPalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayPalActionPerformed
        pg = pp;
        this.ErrorLabel.setText("");
        String entrada = JOptionPane.showInputDialog(this, "Introduzca el correo electronico", "PayPal", JOptionPane.PLAIN_MESSAGE);
        try {
            validacionPayPal(entrada);
        } catch (Exception ex) {
            this.ErrorLabel.setText(ex.getMessage());
        }
    }//GEN-LAST:event_PayPalActionPerformed

    private void PagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagarActionPerformed
        if (pg != null&&pg.get()!=null) {
            String entrada = JOptionPane.showInputDialog(this, "Introduzca Cantidad", "Pagar", JOptionPane.PLAIN_MESSAGE);
            try {
                validacionPago(entrada);
            } catch (Exception ex) {
                this.ErrorLabel.setText(ex.getMessage());
            }
        } else {
            try {
                throw new Exception("No has seleccionado ningun metodo de pago");
            } catch (Exception ex) {
                this.ErrorLabel.setText(ex.getMessage());
            }
        }
    }//GEN-LAST:event_PagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPagos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bizum;
    private javax.swing.JTextField ErrorLabel;
    private javax.swing.JLabel LogoBanco;
    private javax.swing.JPanel Mensajes;
    private javax.swing.JLabel Metodos;
    private javax.swing.JButton Pagar;
    private javax.swing.JTextArea Pantalla;
    private javax.swing.JButton PayPal;
    private javax.swing.JButton Tarjeta;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
